name: feature-pipeline
on:
  push:
  workflow_dispatch:
jobs:
  feature-pipeline:
    if: github.ref_name != 'main'
    uses: 88s-org/workflows/.github/workflows/nodejs-feature-pipeline.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue'
      environment: 'dev'
    secrets: inherit

  main-pipeline:
    if: github.ref_name == 'main'
    uses: 88s-org/workflows/.github/workflows/nodejs-main-pipeline.yaml@main
    with:
      project: 'roboshop'
      component: 'catalogue'
      environment: 'dev'
    secrets: inherit
